# -*- coding: utf-8 -*-
"""Untitled80.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZ7QCPRTVyhT87yXPz85-4YuyjW9i2D9
"""



import smtplib
import os
from email.message import EmailMessage

# email_user = os.environ['rfondufe@gmail.com'] # Remove this line
# email_pass = os.environ['qxjb igqy xnza uqlk'] # Remove this line

email_user = 'rfondufe@gmail.com' # Directly use the email address
email_pass = 'qxjb igqy xnza uqlk' # Directly use the app password

msg = EmailMessage()
msg['Subject'] = 'Daily Arrears Report'
msg['From'] = email_user
msg['To'] = 'renefondufe@yahoo.co.uk'
msg.set_content('Attached is the daily arrears report.')

with open('daily_arrears.csv', 'rb') as f:
    msg.add_attachment(f.read(), maintype='application', subtype='csv', filename='daily_arrears.csv')

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(email_user, email_pass)
    smtp.send_message(msg)
